version: "3"
services:
  stock_management_backend_services:
    hostname: stock_management_backend_services
    container_name: stock_management_backend_services
    environment:
      - NODE_ENV=local
      - DATABASE_URL=postgres://admin:admin@stock_management_postgres_services:5432/stock_management
    user: "root"
    ports:
      - 8998:8998
      - 5555:5555 # for prisma studio
    build:
      context: .
      dockerfile: ${PWD}/docker/backend/Dockerfile
    volumes:
      - ./backend/:/home/app/
      - ./libs/:/home/app/libs/
    depends_on:
      - stock_management_postgres_services

  stock_management_frontend_services:
    hostname: stock_management_frontend_services
    container_name: stock_management_frontend_services
    environment:
      - NODE_ENV=local
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ${PWD}/docker/frontend/Dockerfile
    volumes:
      - ./frontend/:/home/app/
      - ./libs/:/home/app/libs/
    depends_on:
      - stock_management_backend_services

  stock_management_postgres_services:
    image: postgres:latest
    hostname: stock_management_postgres_services
    container_name: stock_management_postgres_services
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=stock_management
    ports:
      - 5432:5432

networks:
  default:
    name: stock_management
